### ISSUE TITLE
Graphing the output?

### ISSUE THREAD

**Issue by beaugunderson** [mddub/gmail-logger#1]
Hey Mark, do you have the code used to make the graphs from your presentation available? Figured I'd ask before reinventing the wheel. :)

**Comment by mddub** [comment]
Hey Beau, I do! It needs a little bit of love to make it comprehensible and usable by others.

See https://github.com/mddub/gmail-graphs. I've put the code for Figure 3 up; the other two are coming soon. I'll close this issue after I get a chance to post the others.

**Comment by mddub** [comment]
Finally got around to cleaning up the code for the other graphs. Please try it out! Naturally, I have no idea how it will work on others' data, so feel free to file an issue/submit a PR on `gmail-graphs`.
